/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  prereqs: [
    {
      type: 'autogenerated',
      dirName: '01-Getting-Started'
    }
  ],
  angular101: [
    {
      type: 'autogenerated',
      dirName: '02-Angular-101'
  }  
  ],
  realWorld: [
    {
      type: 'autogenerated',
      dirName: '03-Getting-Real'
    }
  ]
};

module.exports = sidebars;
